params:
  paths:
    workspace_directory: /Users/hachimhassani/projects/etljobs/sql2json2api/usecasesConfig/am
spring:
  datasource:
    url: jdbc:mysql://localhost:3360/api-celio?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  sql:
    #directory: /Users/hachimhassani/projects/etljobs/sql2json2api/usecasesConfig/am/sql
    directory: ${params.paths.workspace_directory}/sql
    # Liste des fichiers SQL à exécuter dans l'ordre spécifié
    # Si la liste est vide, tous les fichiers sont exécutés
    execution-order:
      # - "GET_users.sql"
      # - "POST_order.sql"
      # - "GET_toto_non_existant.sql"
      # - "TEST_httpbin.sql"
      - "POST_product_groups.sql"

# logging:
#   level:
#     root: INFO
#     com.etljobs.sql2json2api: DEBUG
#     org.springframework.jdbc.core: DEBUG