spring:
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: embedded

app:
  sql:
    directory: sql
  template:
    directory: templates/json
  batch:
    size: 5
    delay: 1000

# Configuration pour utiliser httpbin.org comme API de test
api:
  auth:
    url: https://httpbin.org/post  # Utilisé pour simuler l'authentification
    username: demo_user
    password: demo_password
    token-ttl: 3600

logging:
  level:
    root: INFO
    com.etljobs.sql2json2api: DEBUG
    org.springframework.jdbc.core: INFO
    org.springframework.web.client: DEBUG  # Pour voir les détails des appels HTTP