spring:
  datasource:
    url: jdbc:mysql://localhost:3360/sql2json2api?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always

app:
  sql:
    directory: sql
  template:
    directory: templates/json
  batch:
    size: 10
    delay: 500
api:
  auth:
    url: http://api-celio.127.0.0.1.traefik.me/api/authenticate
    username: admin_api
    password: gnDLta18o53x+4+/+MH/R/jX06V
    token-ttl: 3600
    # Template JSON pour le payload d'authentification
    # Peut contenir des placeholders: ${username}, ${password} pour les informations d'authentification
    payload-template: >
      {
        "username": "${username}",
        "password": "${password}",
        "context": "api"
      }

logging:
  level:
    root: INFO
    com.etljobs.sql2json2api: DEBUG
    org.springframework.jdbc.core: DEBUG