spring:
  datasource:
    url: ${DATASOURCE_URL}  # Format: jdbc:mysql://host:port/db_name - Autres: jdbc:postgresql://, jdbc:oracle:thin:@, jdbc:h2:mem:
    username: ${DATASOURCE_USERNAME}  # Nom d'utilisateur pour la connexion à la base de données
    password: ${DATASOURCE_PASSWORD}  # Mot de passe pour la connexion à la base de données
    driver-class-name: com.mysql.cj.jdbc.Driver  # Autres drivers: org.postgresql.Driver, oracle.jdbc.OracleDriver, org.h2.Driver, com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop  # Options: create, create-drop, update, validate, none
    show-sql: true  # Options: true, false - Affiche les requêtes SQL exécutées
    properties:
      hibernate:
        format_sql: true  # Options: true, false - Formate les requêtes SQL pour lisibilité
    database-platform: org.hibernate.dialect.MySQLDialect  # Autres: PostgreSQLDialect, OracleDialect, H2Dialect, com.microsoft.sqlserver.jdbc.SQLServerDriver
  sql:
    init:
      mode: always  # Options: always, embedded, never - Contrôle l'exécution des scripts SQL d'initialisation

app:
  sql:
    directory: sql  # Chemin vers le répertoire des fichiers SQL (relatif ou absolu)
    execution-order:  # Liste ordonnée des fichiers SQL à exécuter, vide = tous les fichiers dans l'ordre alphabétique
      - "GET_users.sql"
      - "POST_order.sql"
      - "GET_toto_non_existant.sql"
      - "TEST_httpbin.sql"
  template:
    directory: templates/json  # Chemin vers le répertoire des templates FreeMarker (relatif ou absolu)
  batch:
    size: 10  # Entier positif - Nombre d'éléments traités par lot
    delay: 500  # Entier positif - Délai entre les lots en millisecondes
  retry:
    max-attempts: 3  # Entier positif - Nombre maximum de tentatives (1 = pas de réessai)
    delay-ms: 2000  # Entier positif - Délai initial entre les tentatives en millisecondes
    backoff-multiplier: 1.5  # Nombre > 1.0 - Facteur multiplicatif pour le délai à chaque nouvel essai

api:
  auth:
    url: ${API_BASE_URL}${API_AUTH_ROUTE}  # URL complète du point de terminaison d'authentification
    username: ${API_AUTH_USERNAME}  # Nom d'utilisateur pour l'authentification API
    password: ${API_AUTH_PASSWORD}  # Mot de passe pour l'authentification API
    token-ttl: ${API_AUTH_TOKEN_TTL}  # Entier positif - Durée de vie du token en secondes
    payload-template-path: auth-payload.ftlh  # Chemin vers le template du payload d'authentification (relatif à app.template ou absolu)
  base-url: ${API_BASE_URL}  # URL de base commune pour tous les appels API

logging:
  level:
    root: INFO  # Options: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
    com.etljobs.sql2json2api: DEBUG  # Niveau de log spécifique pour les classes de l'application
    org.springframework.jdbc.core: DEBUG  # Niveau de log spécifique pour les opérations JDBC