spring:
  datasource:
    url: jdbc:mysql://localhost:3360/api-celio?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always

app:
  paths:
    # Mode de résolution des chemins: classpath, absolute, relative 
    resolution-mode: relative
    # Chemin des fichiers SQL
    sql-directory: sql
    # Chemin des templates Freemarker
    template-directory: templates/json
    # Chemin du template d'authentification
    auth-template-path: templates/auth/auth-payload.ftlh
  
  # Configuration des requêtes SQL
  sql:
    # Liste des fichiers SQL à exécuter dans l'ordre spécifié
    execution-order:
      - "POST_product_groups.sql"
  
  # Configuration des traitements par lot
  batch:
    size: 10
    delay: 500
  
  # Configuration des réessais
  retry:
    max-attempts: 3
    delay-ms: 2000
    backoff-multiplier: 1.5

# Configuration API
api:
  auth:
    url: http://api-celio.127.0.0.1.traefik.me/api/authenticate
    username: admin_api
    password: gnDLta18o53x+4+/+MH/R/jX06V
    token-ttl: 1 # 3600 en production
  base-url: http://api-celio.127.0.0.1.traefik.me # URL de base pour les appels API

logging:
  level:
    root: INFO
    com.etljobs.sql2json2api: DEBUG
    org.springframework.jdbc.core: DEBUG